# Main Colors
unrecognized_file: tan
recognized_file: darkorange
executable_file: lime
dir: dodgerblue

# Link
dead_link: crimson
link: deepskyblue

# special files
socket: green
blockdev: green
chardev: green
hidden: burlywood
hidden_dir: slategray

# Access Modes
write: tan
read: green
exec: red
no_access: crimson

# Age
day_old: green
hour_old: lime
no_modifier: green

# File Size
file_large: mediumblue
file_medium: dodgerblue
file_small: deepskyblue

# Random
report: white
user: crimson
tree: cyan
empty: darkorange
error: crimson
normal: tan
inode: moccasin

# Git
addition: chartreuse
modification: darkkhaki
deletion: darkred
untracked: darkorange
unchanged: forestgreen
# Colors to be used
## crimson - dark red/rose
## darkgray
## darkorange
## dodgerblue
## deepskyblue
## green
## mediumblue
## lime

