"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 750
add_newline = true
palette = "nightowl"

format = """
[](fg:grey)\
$os\
[](bg:cherry fg:grey)\
$directory\
[](bg:fuscia fg:cherry)\
$git_branch\
$git_status\
[](fg:fuscia bg:yellow)\
$git_state\
$status\

"""

right_format = """
[](fg:blue)\
$c\
$dart\
$java\
$nodejs\
$python\
[](fg:grey bg:blue)\
$time\
[](fg:grey)
"""

# $git_state\ https://starship.rs/config/#git-state
# $docker_context\ https://starship.rs/config/#docker-context

[os]
style = "bg:grey fg:white"
format = '[$symbol]($style)'
disabled = false

[os.symbols]
CentOS = " "
Debian = " "
Fedora = " "
Gentoo = " "
Linux = " "
Macos = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Windows = " "
Unknown = "? "

[directory]
style = "bg:cherry fg:white"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
'~/Projects/Software' = ''

[git_branch]
symbol = ""
style = "bg:fuscia fg:white"
format = '[ $symbol $branch ]($style)'
truncation_length = 10

[git_status]
style = "bg:fuscia fg:white"
format = '[$all_status$ahead_behind]($style)'
conflicted = ' '
ahead = ' '
behind = ' '
diverged = '󰃻 '
up_to_date = '󰗠 '
untracked = '󰋗 '
stashed = ' '
modified = ' '
staged = " "
renamed = ' '
deleted = ' '

[git_state]
style = "bg:yellow fg:white"

[c]
symbol = " "
style = "bg:blue fg:white"
format = "[ $symbol ($version) ]($style)"
version_format = "${major}.${minor}"

[java]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[lua]
symbol = ""
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[nodejs]
symbol = "󰎙"
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[python]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[dart]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[ruby]
symbol = " "
style = "bg:blue fg:white"
format = '[ $symbol ($version) ]($style)'
version_format = "${major}.${minor}"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:grey fg:white"
format = '[  $time ]($style)'

[status]
style = 'bg:yellow fg:white'
symbol = '[](fg:yellow bg:cherry)[](fg:cherry)'
success_symbol = '[](fg:yellow bg:green)[](fg:green)'
not_executable_symbol = '[](fg:yellow bg:red)[ 󰜺 ](bg:red)[](fg:red)'
not_found_symbol = '[](fg:yellow bg:fuscia)[ ? ](bg:fuscia)[](fg:fuscia)'
sigint_symbol = '[](fg:yellow bg:yellow)[  ](bg:yellow)[](fg:yellow)'
signal_symbol = '[](fg:yellow bg:blue)[ 󰙎 ](bg:blue)[](fg:blue)'
format = '$symbol '
map_symbol = true
disabled = false

[palettes.nightowl]
fuscia = "#A51583"
cherry = "#B71D49"
blue = "#0087D5"
yellow = "#E2A200"
tan = "#CBB794"
red = "#A51024"
green = "#05A505"
white = "#F1F1F1"
grey = "#282828"
