#!/bin/sh

# Improvements to existing commands
alias cat="bat --theme auto:system --theme-dark default --theme-light GitHub"
alias git='LANG=en_US.UTF-8 git'

# New useful commands
alias l="colorls"
alias la="colorls -1A --group-directories-first"
alias ll="colorls -lA --group-directories-first"
alias lt="colorls -A --tree=2 --group-directories-first"
alias lg="colorls -A --git-status --group-directories-first"
alias pip='pipx'
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias py="python3"
alias reload='source "${HOME}/.zshrc" && echo "sourced ${HOME}/.zshrc"'
alias update="brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; gem update --system"
alias vi="nvim"
alias edit="nvim"
