#!/bin/sh

alias cat="bat --theme auto:system --theme-dark default --theme-light GitHub"
alias git='LANG=en_US.UTF-8 git'
alias pip='pipx'
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"
alias reload='source "${HOME}/.zshrc" && echo "sourced ${HOME}/.zshrc"'
alias update="brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g; gem update --system"
alias vi="nvim"

alias l="colorls"
alias la="colorls -a"
alias ll="colorls -lA"
alias lt="colorls --tree=2"
alias lc='colorls -lA --sd'
