# General PATH exports
PATH=/bin:/usr/bin:/usr/local/bin:/sbin:${PATH}
export PATH=/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# LaTex PATH
export PATH="/usr/libexec/path_helper:$PATH"
export PATH="/usr/local/texlive/2025/bin/universal-darwin/:$PATH"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins
plugins=(
  brew
  colorize
  common-aliases
  git
  iterm2
  macos
  nvm
  pip
  yarn
  zsh-navigation-tools
  zsh-interactive-cd
)

source $ZSH/oh-my-zsh.sh

# Navigation tools
autoload znt-history-widget
zle -N znt-history-widget
bindkey "^R" znt-history-widget

# iTerm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Alias
alias pip='pipx'
alias reload='source "${HOME}/.zshrc" && echo "sourced ${HOME}/.zshrc"'
alias update="brew update; brew upgrade; brew cleanup; npm update npm -g; npm update -g"

# Starship
eval "$(starship init zsh)"